export type InputFormat = 'png' | 'jpg' | 'webp'
export type OutputFormat = 'png' | 'jpg' | 'webp' | 'avif'
export type ConversionId =
  | 'png-webp'
  | 'png-jpg'
  | 'png-avif'
  | 'jpg-png'
  | 'jpg-webp'
  | 'jpg-avif'
  | 'webp-png'
  | 'webp-jpg'
  | 'webp-avif'
